### ISSUE TITLE
Public key

### ISSUE THREAD

**Issue by Danielix99** [seishun/node-steam-crypto#3]
hi, i've recently tried to create a port of your project in c# but i wanna retrieve the public key myself and tried to take the public key from steamcommunity or steampowered ssl cert, but when i check mine pubkey with your i see thats completely different, then the question is: how did you retrieved that key?

**Comment by seishun** [comment]
I took the key from [SteamKit2](https://github.com/SteamRE/SteamKit/blob/d9a1da3513e2747dbe2c3d752aebf7464e2d900b/SteamKit2/SteamKit2/Util/KeyDictionary.cs#L22) and just converted it to PEM. I have no idea where they got it, probably by disassembling Steam. @voided might be able to tell you more about it.

**Comment by voided** [comment]
The public key used for the steam client's crypto is baked into the steamclient.dll/dylib/so library. I don't recall what format it's stored in the library, or if we transformed it after extracting it, however.

**Comment by Danielix99** [comment]
thanks for the info guys
